"""Self-contained HTML dashboard for the Stage A metric history.

Two views from metrics_history.csv: the full metric table for one selected
run (grouped context / holdout-fit / simulation), and per-metric charts
across iterations (per-user series, ±sd replicate bars, target bands, real
holdout references). Written to the git-ignored meta/ dir next to the PNG --
per-user numbers stay with the data, never in tracked files or external
hosts. Regenerated by stage_a_metrics.py --report, or standalone:

    python stage_a_dashboard.py [--history PATH] [--out PATH]

Everything is inlined (data as JSON, vanilla-JS SVG charts), so the file
opens from file:// with no network access.
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from stage_a_metrics import (DEFAULT_HISTORY, DEFAULT_META_DIR,
                             FIT_METRIC_SUFFIXES, KEY_METRIC_PAIRS,
                             PAIR_COLUMN_HEADS, REFERENCE, SIM_METRICS,
                             _run_order, metric_description)

DASHBOARD_FILENAME = "dashboard.html"
USER_COLORS = ["#2a78d6", "#eb6834", "#1baf7a"]  # categorical slots 1-3
                                                 # (palette validated together)


def _payload(hist):
    order = _run_order(hist)
    runs = []
    for label in order:
        h = hist[hist["run_label"] == label]
        try:
            config = json.loads(h["config"].iloc[0])
        except (TypeError, ValueError):
            config = {}
        note = h["note"].iloc[0] if "note" in h.columns else ""
        runs.append({"label": label, "ts": h["run_ts"].min(),
                     "commit": h["git_commit"].iloc[0], "config": config,
                     "note": note if isinstance(note, str) else ""})

    rows = hist[["run_label", "user", "metric", "value", "sd"]].copy()
    rows = rows.astype(object).where(rows.notna(), None)
    metric_order = list(dict.fromkeys(hist["metric"]))

    def _tier(metric):
        if metric in SIM_METRICS:
            return "simulation"
        if metric.endswith(FIT_METRIC_SUFFIXES):
            return "fit"
        return "context"

    return {
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "runs": runs,
        "users": sorted(hist["user"].unique()),
        "metric_order": metric_order,
        "tiers": {m: _tier(m) for m in metric_order},
        "descriptions": {m: metric_description(m) for m in metric_order},
        "rows": rows.to_dict("records"),
        "key_metric_pairs": KEY_METRIC_PAIRS,
        "pair_column_heads": list(PAIR_COLUMN_HEADS),
        "reference": REFERENCE,
        "user_colors": USER_COLORS,
    }


def build_dashboard(history_path=DEFAULT_HISTORY, out_path=None):
    if out_path is None:
        out_path = os.path.join(DEFAULT_META_DIR, DASHBOARD_FILENAME)
    hist = pd.read_csv(history_path)
    html = _TEMPLATE.replace("__DATA__", json.dumps(_payload(hist)))
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(html)
    print(f"    {out_path}")
    return out_path


_TEMPLATE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Stage A metrics dashboard</title>
<style>
  :root {
    --ink: #0b0b0b; --sec: #52514e; --mut: #898781;
    --grid: #e1e0d9; --baseline: #c3c2b7;
    --surface: #fcfcfb; --page: #f4f3ef; --band: #f0efec;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 24px 28px 48px; background: var(--page);
    color: var(--ink);
    font: 14px/1.45 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  }
  h1 { font-size: 19px; font-weight: 650; margin: 0 0 2px; }
  h2 { font-size: 15px; font-weight: 650; margin: 34px 0 10px; }
  .sub { color: var(--mut); font-size: 12px; margin-bottom: 18px; }
  .controls { display: flex; gap: 14px; align-items: center; flex-wrap: wrap;
              margin: 14px 0 6px; }
  .controls label { color: var(--sec); font-size: 13px; }
  select { font: inherit; padding: 4px 8px; border: 1px solid var(--baseline);
           border-radius: 6px; background: var(--surface); color: var(--ink); }
  .config { color: var(--mut); font-size: 12px; margin: 4px 0 2px; }
  .note { color: var(--sec); font-size: 13px; font-style: italic;
          margin: 0 0 14px; max-width: 900px; }
  .legend { display: flex; gap: 18px; margin: 6px 0 12px; flex-wrap: wrap; }
  .legend span { color: var(--sec); font-size: 12.5px; display: inline-flex;
                 align-items: center; gap: 6px; }
  .dot { width: 9px; height: 9px; border-radius: 50%; display: inline-block; }
  table { border-collapse: collapse; background: var(--surface);
          border: 1px solid var(--grid); border-radius: 8px; overflow: hidden; }
  th, td { padding: 5px 14px; font-size: 13px; text-align: right;
           border-bottom: 1px solid var(--grid); }
  th { color: var(--sec); font-weight: 600; }
  td:first-child, th:first-child { text-align: left; }
  td.metric { color: var(--sec); cursor: help;
              text-decoration: underline dotted var(--baseline);
              text-underline-offset: 3px; }
  tr.tier td { background: var(--band); color: var(--mut); font-size: 11.5px;
               text-transform: uppercase; letter-spacing: 0.06em;
               text-align: left; }
  .panels { display: grid; grid-template-columns: repeat(2, max-content);
            gap: 18px; overflow-x: auto; }
  .colhead { color: var(--sec); font-size: 13px; font-weight: 650;
             text-transform: uppercase; letter-spacing: 0.06em;
             padding-left: 12px; }
  .panel { background: var(--surface); border: 1px solid var(--grid);
           border-radius: 8px; padding: 10px 14px 2px; }
  .panel .ptitle { color: var(--sec); font-size: 12.5px; margin: 0 0 2px 10px;
                   cursor: help; display: inline-block;
                   text-decoration: underline dotted var(--baseline);
                   text-underline-offset: 3px; }
  .panel svg { overflow: visible; }  /* rotated x labels may exceed the box */
  #tooltip { position: fixed; display: none; pointer-events: none;
             background: var(--ink); color: #fcfcfb; font-size: 12px;
             padding: 5px 9px; border-radius: 6px; max-width: 320px;
             z-index: 10; }
  #tooltip .t2 { color: #c3c2b7; }
</style>
</head>
<body>
<h1>Stage A metrics dashboard</h1>
<div class="sub" id="sub"></div>

<div class="controls">
  <label for="runsel">Run</label>
  <select id="runsel"></select>
  <div class="legend" id="legend"></div>
</div>
<div class="config" id="config"></div>
<div class="note" id="runnote"></div>

<h2>Metrics for the selected run</h2>
<div style="overflow-x:auto"><table id="runtable"></table></div>

<h2>Metrics across iterations <span style="color:var(--mut);font-weight:400;
  font-size:12px">(bars: ±sd over simulation replicates; dotted: real holdout
  reference; dash-dot: surrogate floors — "binomial" = constant-rate,
  "clock" = hour-of-day rate; shaded: acceptance band)</span></h2>
<div class="panels" id="panels"></div>

<h2>Iteration log</h2>
<div style="overflow-x:auto"><table id="runlog"></table></div>
<div id="tooltip"></div>

<script>
const DATA = __DATA__;

const ORDER = DATA.runs.map(r => r.label);
const USERS = DATA.users;
// per-user hue identity caps at the validated palette (hues are never
// cycled); beyond it, panels switch to muted per-user lines + a median line,
// with identity available via hover and the run table
const SPAGHETTI = USERS.length > DATA.user_colors.length;
const GRAY = "#898781";
const COLOR = Object.fromEntries(USERS.map((u, i) =>
  [u, SPAGHETTI ? GRAY : DATA.user_colors[i]]));
const median = arr => {
  const v = arr.filter(x => x !== null && x !== undefined && !Number.isNaN(x))
    .sort((a, b) => a - b);
  if (!v.length) return null;
  const m = Math.floor(v.length / 2);
  return v.length % 2 ? v[m] : (v[m - 1] + v[m]) / 2;
};
const CELL = {};   // run -> user -> metric -> {value, sd}
for (const row of DATA.rows) {
  ((CELL[row.run_label] ??= {})[row.user] ??= {})[row.metric] = row;
}
const fmt = v => (v === null || v === undefined || Number.isNaN(v)) ? "–"
  : String(Number(Number(v).toPrecision(4)));
const cellText = c => !c || c.value === null ? "–"
  : fmt(c.value) + (c.sd !== null && c.sd !== undefined ? " ±" + Number(Number(c.sd).toPrecision(2)) : "");

const TIER_LABEL = {context: "Context", fit: "Holdout fit (one-step-ahead)",
                    simulation: "Simulation (free-running, mean ±sd)"};
function tier(metric) { return TIER_LABEL[DATA.tiers[metric]] || "Context"; }

function renderSub() {
  document.getElementById("sub").textContent =
    `generated ${DATA.generated} · ${DATA.runs.length} run(s) · ${USERS.length} user(s)`;
  const leg = document.getElementById("legend");
  leg.innerHTML = SPAGHETTI
    ? `<span><span class="dot" style="background:${GRAY};opacity:.5"></span>` +
      `individual users (n=${USERS.length}, hover for identity)</span>` +
      `<span><span class="dot" style="background:${DATA.user_colors[0]}"></span>` +
      `median across users</span>`
    : USERS.map(u =>
      `<span><span class="dot" style="background:${COLOR[u]}"></span>${u}</span>`).join("");
  const sel = document.getElementById("runsel");
  sel.innerHTML = ORDER.map(l => `<option value="${l}">${l}</option>`).join("");
  sel.value = ORDER[ORDER.length - 1];
  sel.onchange = render;
}

function renderConfig(run) {
  const r = DATA.runs.find(x => x.label === run);
  const s = r.config.split || {};
  document.getElementById("config").textContent =
    `recorded ${r.ts} · commit ${r.commit} · split ${s.type ?? "?"} ` +
    `(train_frac ${s.train_frac ?? "?"}) · n_sims ${r.config.n_sims ?? "?"}` +
    ` · comparisons are like-for-like only within a split regime`;
  document.getElementById("runnote").textContent = r.note || "";
}

function renderRunLog(selectedRun) {
  const t = document.getElementById("runlog");
  t.innerHTML = `<tr><th>iteration</th><th>recorded</th><th>split</th>` +
    `<th style="text-align:left">note</th></tr>` +
    DATA.runs.map(r => {
      const s = r.config.split || {};
      const bold = r.label === selectedRun ? "font-weight:650" : "";
      return `<tr><td style="text-align:left;${bold}">${r.label}</td>` +
        `<td>${String(r.ts).slice(0, 10)}</td>` +
        `<td>${s.type ?? "?"}</td>` +
        `<td style="text-align:left;color:var(--sec)">${r.note || ""}</td></tr>`;
    }).join("");
}

function renderTable(run) {
  const t = document.getElementById("runtable");
  let html = `<tr><th>metric</th>${USERS.map(u => `<th>${u}</th>`).join("")}</tr>`;
  let lastTier = null;
  for (const m of DATA.metric_order) {
    const tr = tier(m);
    if (tr !== lastTier) {
      html += `<tr class="tier"><td colspan="${USERS.length + 1}">${tr}</td></tr>`;
      lastTier = tr;
    }
    html += `<tr><td class="metric" data-m="${m}">${m}</td>` +
      USERS.map(u => `<td>${cellText(CELL[run]?.[u]?.[m])}</td>`).join("") + `</tr>`;
  }
  t.innerHTML = html;
  for (const td of t.querySelectorAll("td.metric")) {
    const m = td.dataset.m;
    const desc = DATA.descriptions[m];
    if (!desc) continue;
    td.addEventListener("mousemove", evt => showTip(evt, [m, desc]));
    td.addEventListener("mouseleave", hideTip);
  }
}

const TT = document.getElementById("tooltip");
function showTip(evt, lines) {
  TT.innerHTML = lines.map((l, i) => i ? `<div class="t2">${l}</div>` : `<div>${l}</div>`).join("");
  TT.style.display = "block";
  TT.style.left = Math.min(evt.clientX + 14, innerWidth - 340) + "px";
  TT.style.top = (evt.clientY + 14) + "px";
}
function hideTip() { TT.style.display = "none"; }

function svgEl(tag, attrs) {
  const el = document.createElementNS("http://www.w3.org/2000/svg", tag);
  for (const [k, v] of Object.entries(attrs)) el.setAttribute(k, v);
  return el;
}

function panel(metric, title, selectedRun) {
  const W = 540, H = 300, L = 52, R = 14, T = 12, B = 66;
  const ref = DATA.reference[metric] || {};
  const series = USERS.map(u => ({
    user: u,
    pts: ORDER.map(run => CELL[run]?.[u]?.[metric] ?? null),
    real: ref.real_ref ? ORDER.map(run => CELL[run]?.[u]?.[ref.real_ref] ?? null) : null,
  }));

  // surrogate floors: cross-user median per run, drawn as labeled dash-dot
  // references ("binomial" = constant-rate, "clock" = hour-of-day-rate)
  const surrFloors = (ref.surr_refs || []).map(([m, label]) => ({
    label,
    vals: ORDER.map(run =>
      median(USERS.map(u => (CELL[run]?.[u]?.[m] ?? {}).value ?? null))),
  })).filter(f => f.vals.some(v => v !== null));

  const vals = [];
  for (const s of series) {
    for (const p of s.pts) if (p && p.value !== null) {
      vals.push(p.value); if (p.sd) { vals.push(p.value + p.sd, p.value - p.sd); }
    }
    if (s.real) for (const p of s.real) if (p && p.value !== null) vals.push(p.value);
  }
  for (const f of surrFloors) for (const v of f.vals) if (v !== null) vals.push(v);
  if (ref.band) vals.push(ref.band[0], ref.band[1]);
  if (ref.line !== undefined) vals.push(ref.line);
  if (!vals.length) return null;
  let lo = Math.min(...vals), hi = Math.max(...vals);
  if (lo === hi) { lo -= 0.5; hi += 0.5; }
  const pad = (hi - lo) * 0.09; lo -= pad; hi += pad;

  const x = i => L + (ORDER.length === 1 ? (W - L - R) / 2
    : i * (W - L - R) / (ORDER.length - 1));
  const y = v => T + (H - T - B) * (1 - (v - lo) / (hi - lo));

  const div = document.createElement("div");
  div.className = "panel";
  div.innerHTML = `<div><span class="ptitle">${title}</span></div>`;
  const desc = DATA.descriptions[metric];
  if (desc) {
    const pt = div.querySelector(".ptitle");
    pt.addEventListener("mousemove", evt => showTip(evt, [metric, desc]));
    pt.addEventListener("mouseleave", hideTip);
  }
  const svg = svgEl("svg", {width: W, height: H});
  div.appendChild(svg);

  if (ref.band) svg.appendChild(svgEl("rect", {
    x: L, y: y(ref.band[1]), width: W - L - R,
    height: Math.max(0, y(ref.band[0]) - y(ref.band[1])),
    fill: "var(--band)"}));
  for (let t = 0; t < 4; t++) {                       // y grid + labels
    const v = lo + (hi - lo) * t / 3;
    svg.appendChild(svgEl("line", {x1: L, x2: W - R, y1: y(v), y2: y(v),
      stroke: "var(--grid)", "stroke-width": 0.8}));
    const lab = svgEl("text", {x: L - 6, y: y(v) + 3.5, "text-anchor": "end",
      fill: "var(--mut)", "font-size": 10});
    lab.textContent = fmt(v);
    svg.appendChild(lab);
  }
  if (ref.line !== undefined) svg.appendChild(svgEl("line", {
    x1: L, x2: W - R, y1: y(ref.line), y2: y(ref.line),
    stroke: "var(--baseline)", "stroke-dasharray": "5 4"}));

  for (const f of surrFloors) {
    const seg = f.vals.map((v, i) => v !== null ? `${x(i)},${y(v)}` : null)
      .filter(Boolean);
    svg.appendChild(svgEl("polyline", {points: seg.join(" "), fill: "none",
      stroke: GRAY, "stroke-width": 1.1, "stroke-dasharray": "4 2 1 2"}));
    let last = null;
    f.vals.forEach((v, i) => { if (v !== null) {
      svg.appendChild(svgEl("rect", {x: x(i) - 2.5, y: y(v) - 2.5, width: 5,
        height: 5, fill: "none", stroke: GRAY}));
      last = [x(i), y(v)];
    }});
    if (last) {
      const lab = svgEl("text", {x: last[0] + 5, y: last[1] - 4,
        fill: "var(--mut)", "font-size": 9});
      lab.textContent = f.label;
      svg.appendChild(lab);
    }
  }

  ORDER.forEach((run, i) => {                         // x labels
    const lab = svgEl("text", {
      x: x(i), y: H - B + 16, fill: run === selectedRun ? "var(--ink)" : "var(--mut)",
      "font-size": 10, "font-weight": run === selectedRun ? 650 : 400,
      transform: `rotate(-28 ${x(i)} ${H - B + 16})`, "text-anchor": "end"});
    lab.textContent = run;
    svg.appendChild(lab);
  });

  if (SPAGHETTI) {
    const seg = pts => pts.filter(p => p !== null).join(" ");
    for (const s of series) {
      svg.appendChild(svgEl("polyline", {
        points: seg(s.pts.map((p, i) => p && p.value !== null ? `${x(i)},${y(p.value)}` : null)),
        fill: "none", stroke: GRAY, "stroke-width": 0.9, opacity: 0.4}));
    }
    const med = i => median(series.map(s => s.pts[i] ? s.pts[i].value : null));
    if (ref.real_ref) {
      const rmed = i => median(series.map(s => s.real && s.real[i] ? s.real[i].value : null));
      svg.appendChild(svgEl("polyline", {
        points: seg(ORDER.map((_, i) => rmed(i) !== null ? `${x(i)},${y(rmed(i))}` : null)),
        fill: "none", stroke: DATA.user_colors[0], "stroke-width": 1.2,
        opacity: 0.7, "stroke-dasharray": "2 3"}));
      ORDER.forEach((_, i) => { const v = rmed(i); if (v !== null)
        svg.appendChild(svgEl("circle", {cx: x(i), cy: y(v), r: 3,
          fill: "none", stroke: DATA.user_colors[0], opacity: 0.7})); });
    }
    svg.appendChild(svgEl("polyline", {
      points: seg(ORDER.map((_, i) => med(i) !== null ? `${x(i)},${y(med(i))}` : null)),
      fill: "none", stroke: DATA.user_colors[0], "stroke-width": 2.2}));
    ORDER.forEach((run, i) => { const v = med(i); if (v !== null) {
      const c = svgEl("circle", {cx: x(i), cy: y(v), r: 4,
        fill: DATA.user_colors[0], stroke: "var(--surface)", "stroke-width": 1.5});
      svg.appendChild(c);
    }});
    // identity via hover: a hit circle on every user point
    for (const s of series) s.pts.forEach((p, i) => {
      if (!p || p.value === null) return;
      const hit = svgEl("circle", {cx: x(i), cy: y(p.value), r: 7,
        fill: "transparent"});
      hit.addEventListener("mousemove", evt =>
        showTip(evt, [`${s.user} — ${ORDER[i]}`, `${metric}: ${cellText(p)}`]));
      hit.addEventListener("mouseleave", hideTip);
      svg.appendChild(hit);
    });
    return div;
  }

  series.forEach((s, si) => {
    const off = (si - (USERS.length - 1) / 2) * 5;
    const col = COLOR[s.user];
    if (s.real) {
      const seg = s.real.map((p, i) => p && p.value !== null ? `${x(i) + off},${y(p.value)}` : null);
      svg.appendChild(svgEl("polyline", {points: seg.filter(Boolean).join(" "),
        fill: "none", stroke: col, "stroke-width": 1, opacity: 0.55,
        "stroke-dasharray": "2 3"}));
      s.real.forEach((p, i) => { if (p && p.value !== null) svg.appendChild(svgEl("circle",
        {cx: x(i) + off, cy: y(p.value), r: 3, fill: "none", stroke: col,
         opacity: 0.55})); });
    }
    const seg = s.pts.map((p, i) => p && p.value !== null ? `${x(i) + off},${y(p.value)}` : null);
    svg.appendChild(svgEl("polyline", {points: seg.filter(Boolean).join(" "),
      fill: "none", stroke: col, "stroke-width": 1.8}));
    s.pts.forEach((p, i) => {
      if (!p || p.value === null) return;
      const cx = x(i) + off;
      if (p.sd) {
        svg.appendChild(svgEl("line", {x1: cx, x2: cx, y1: y(p.value - p.sd),
          y2: y(p.value + p.sd), stroke: col, "stroke-width": 1}));
        for (const e of [p.value - p.sd, p.value + p.sd])
          svg.appendChild(svgEl("line", {x1: cx - 3, x2: cx + 3, y1: y(e), y2: y(e),
            stroke: col, "stroke-width": 1}));
      }
      svg.appendChild(svgEl("circle", {cx, cy: y(p.value), r: 3.5, fill: col,
        stroke: "var(--surface)", "stroke-width": 1.5}));
      const hit = svgEl("circle", {cx, cy: y(p.value), r: 11, fill: "transparent"});
      hit.addEventListener("mousemove", evt => {
        const lines = [`${s.user} — ${ORDER[i]}`, `${metric}: ${cellText(p)}`];
        if (s.real && s.real[i] && s.real[i].value !== null)
          lines.push(`real holdout: ${fmt(s.real[i].value)}`);
        showTip(evt, lines);
      });
      hit.addEventListener("mouseleave", hideTip);
      svg.appendChild(hit);
    });
  });
  return div;
}

function renderPanels(selectedRun) {
  const host = document.getElementById("panels");
  host.innerHTML = "";
  for (const head of DATA.pair_column_heads) {
    const d = document.createElement("div");
    d.className = "colhead";
    d.textContent = head;
    host.appendChild(d);
  }
  for (const pair of DATA.key_metric_pairs)
    for (const [metric, title] of pair)
      // empty placeholder keeps the two-column pairing aligned when one
      // side has no data yet
      host.appendChild(panel(metric, title, selectedRun) ??
                       document.createElement("div"));
}

function render() {
  const run = document.getElementById("runsel").value;
  renderConfig(run);
  renderTable(run);
  renderPanels(run);
  renderRunLog(run);
}

renderSub();
render();
</script>
</body>
</html>
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--history", default=DEFAULT_HISTORY)
    parser.add_argument("--out", default=None,
                        help=f"output path (default meta/{DASHBOARD_FILENAME})")
    args = parser.parse_args()
    build_dashboard(args.history, args.out)
