"""Self-contained HTML dashboard for the Stage A metric history.

Main page, from metrics_history.csv (+ roc_history.csv when present):
a selected-run ROC section at the top (holdout one-step-ahead curves --
model vs the clock surrogate vs the chance diagonal, with the recorded
AUCs and a per-user model-vs-clock AUC strip), per-metric charts across
iterations (per-user series, ±sd replicate bars, target bands, real
holdout references, surrogate floors) and a cohort summary of the selected
run (median + IQR across users, grouped context / holdout-fit /
simulation). Per-user numbers live behind a collapsed drill-down -- one
user at a time, metric x iteration, with a link to that user's
trace-browser page. Written to the git-ignored meta/ dir next to the PNG
-- per-user numbers stay with the data, never in tracked files or
external hosts. Regenerated by stage_a_metrics.py --report, or
standalone:

    python stage_a_dashboard.py [--history PATH] [--out PATH]

Everything is inlined (data as JSON, vanilla-JS SVG charts), so the file
opens from file:// with no network access.
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from stage_a_metrics import (DEFAULT_HISTORY, DEFAULT_META_DIR,
                             KEY_METRIC_PAIRS, PAIR_COLUMN_HEADS, REFERENCE,
                             ROC_FILENAME, _run_order, grouped_metric_order,
                             metric_description, metric_tier)

DASHBOARD_FILENAME = "dashboard.html"
USER_COLORS = ["#2a78d6", "#eb6834", "#1baf7a"]  # categorical slots 1-3
                                                 # (palette validated together)


def _user_sets_payload(hist_users):
    """{'train': [[rank, uid], ...], 'dev': ...} from users.csv span-rank
    parity (the user_sets rule), filtered to users in the history; {} when
    the data dir isn't available (standalone --history use), which drops
    the trace strip back to a flat list."""
    try:
        from build_tick_frame import DEFAULT_DATA_DIR, user_sets
        ids = list(pd.read_csv(
            os.path.join(DEFAULT_DATA_DIR, "users.csv"))["_userId"])
    except Exception:
        return {}
    known = set(hist_users)
    rank = {u: i + 1 for i, u in enumerate(ids)}
    return {k: [[rank[u], u] for u in v if u in known]
            for k, v in user_sets(ids).items()}


def _roc_payload(roc):
    """roc_history rows -> {run: {user: {event: {predictor: [[fpr,tpr],..]}}}}
    (vertex order preserved; rounded for payload size)."""
    out = {}
    if roc is None or not len(roc):
        return out
    for (run, user, event, pred), g in roc.groupby(
            ["run_label", "user", "event", "predictor"], sort=False):
        pts = [[round(float(f), 4), round(float(t), 4)]
               for f, t in zip(g["fpr"], g["tpr"])]
        out.setdefault(run, {}).setdefault(user, {}).setdefault(event, {})[pred] = pts
    return out


def _payload(hist, roc=None):
    order = _run_order(hist)
    runs = []
    for label in order:
        h = hist[hist["run_label"] == label]
        try:
            config = json.loads(h["config"].iloc[0])
        except (TypeError, ValueError):
            config = {}
        note = h["note"].iloc[0] if "note" in h.columns else ""
        runs.append({"label": label, "ts": h["run_ts"].min(),
                     "commit": h["git_commit"].iloc[0], "config": config,
                     "note": note if isinstance(note, str) else ""})

    rows = hist[["run_label", "user", "metric", "value", "sd"]].copy()
    rows = rows.astype(object).where(rows.notna(), None)
    metric_order = grouped_metric_order(hist)

    users = sorted(hist["user"].unique())
    return {
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "runs": runs,
        "users": users,
        "user_sets": _user_sets_payload(users),
        "metric_order": metric_order,
        "tiers": {m: metric_tier(m) for m in metric_order},
        "descriptions": {m: metric_description(m) for m in metric_order},
        "rows": rows.to_dict("records"),
        "roc": _roc_payload(roc),
        "key_metric_pairs": KEY_METRIC_PAIRS,
        "pair_column_heads": list(PAIR_COLUMN_HEADS),
        "reference": REFERENCE,
        "user_colors": USER_COLORS,
    }


def build_dashboard(history_path=DEFAULT_HISTORY, out_path=None):
    if out_path is None:
        out_path = os.path.join(DEFAULT_META_DIR, DASHBOARD_FILENAME)
    hist = pd.read_csv(history_path)
    roc_path = os.path.join(os.path.dirname(os.path.abspath(history_path)),
                            ROC_FILENAME)
    roc = pd.read_csv(roc_path) if os.path.exists(roc_path) else None
    html = _TEMPLATE.replace("__DATA__", json.dumps(_payload(hist, roc)))
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(html)
    print(f"    {out_path}")
    return out_path


_TEMPLATE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Stage A metrics dashboard</title>
<style>
  :root {
    --ink: #0b0b0b; --sec: #52514e; --mut: #898781;
    --grid: #e1e0d9; --baseline: #c3c2b7;
    --surface: #fcfcfb; --page: #f4f3ef; --band: #f0efec;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 24px 28px 48px; background: var(--page);
    color: var(--ink);
    font: 14px/1.45 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  }
  h1 { font-size: 19px; font-weight: 650; margin: 0 0 2px; }
  h2 { font-size: 15px; font-weight: 650; margin: 34px 0 10px; }
  .sub { color: var(--mut); font-size: 12px; margin-bottom: 18px; }
  .tracestrip { font-size: 12px; color: var(--mut); margin: -12px 0 14px;
                max-width: 1130px; }
  .tracestrip a { color: var(--sec); text-decoration-color: var(--baseline); }
  .usercols { display: grid; grid-template-columns: repeat(2, max-content);
              gap: 2px 56px; margin-top: 4px; }
  .usercols .setname { color: var(--sec); font-weight: 650; margin-bottom: 2px; }
  .usercols .rk { display: inline-block; min-width: 18px; text-align: right;
                  color: var(--mut); }
  .controls { display: flex; gap: 14px; align-items: center; flex-wrap: wrap;
              margin: 14px 0 6px; }
  .controls label { color: var(--sec); font-size: 13px; }
  select { font: inherit; padding: 4px 8px; border: 1px solid var(--baseline);
           border-radius: 6px; background: var(--surface); color: var(--ink); }
  .config { color: var(--mut); font-size: 12px; margin: 4px 0 2px; }
  .note { color: var(--sec); font-size: 13px; font-style: italic;
          margin: 0 0 14px; max-width: 900px; }
  .legend { display: flex; gap: 18px; margin: 6px 0 12px; flex-wrap: wrap; }
  .legend span { color: var(--sec); font-size: 12.5px; display: inline-flex;
                 align-items: center; gap: 6px; }
  .dot { width: 9px; height: 9px; border-radius: 50%; display: inline-block; }
  table { border-collapse: collapse; background: var(--surface);
          border: 1px solid var(--grid); border-radius: 8px; overflow: hidden; }
  th, td { padding: 5px 14px; font-size: 13px; text-align: right;
           border-bottom: 1px solid var(--grid); }
  th { color: var(--sec); font-weight: 600; }
  td:first-child, th:first-child { text-align: left; }
  td.metric { color: var(--sec); cursor: help;
              text-decoration: underline dotted var(--baseline);
              text-underline-offset: 3px; }
  tr.tier td { background: var(--band); color: var(--mut); font-size: 11.5px;
               text-transform: uppercase; letter-spacing: 0.06em;
               text-align: left; }
  .panels { display: grid; grid-template-columns: repeat(2, max-content);
            gap: 18px; overflow-x: auto; }
  .colhead { color: var(--sec); font-size: 13px; font-weight: 650;
             text-transform: uppercase; letter-spacing: 0.06em;
             padding-left: 12px; }
  .panel { background: var(--surface); border: 1px solid var(--grid);
           border-radius: 8px; padding: 10px 14px 2px; }
  .panel .ptitle { color: var(--sec); font-size: 12.5px; margin: 0 0 2px 10px;
                   cursor: help; display: inline-block;
                   text-decoration: underline dotted var(--baseline);
                   text-underline-offset: 3px; }
  .panel svg { overflow: visible; }  /* rotated x labels may exceed the box */
  details { margin: 8px 0 0; }
  details summary { cursor: pointer; color: var(--sec); font-size: 13.5px;
                    font-weight: 650; margin-bottom: 10px; }
  details a { color: var(--sec); font-size: 13px; }
  #tooltip { position: fixed; display: none; pointer-events: none;
             background: var(--ink); color: #fcfcfb; font-size: 12px;
             padding: 5px 9px; border-radius: 6px; max-width: 320px;
             z-index: 10; }
  #tooltip .t2 { color: #c3c2b7; }
</style>
</head>
<body>
<h1>Stage A metrics dashboard</h1>
<div class="sub" id="sub"></div>
<div class="tracestrip" id="tracestrip"></div>

<div class="controls">
  <label for="runsel">Run</label>
  <select id="runsel"></select>
  <label><input type="checkbox" id="showusers"> per-user lines</label>
  <div class="legend" id="legend"></div>
</div>
<div class="config" id="config"></div>
<div class="note" id="runnote"></div>

<h2>Selected run — ROC <span style="color:var(--mut);font-weight:400;
  font-size:12px">(holdout, one-step-ahead; bold: cross-user median at fixed
  FPR, shaded IQR; dash-dot: recorded surrogate ROCs — clock = hour-of-day
  rate, binomial = constant rate, whose computed curve lies exactly on the
  dashed chance diagonal; per-user curves via the toggle above)</span></h2>
<div class="panels" id="rocpanels"></div>

<h2>Metrics across iterations <span style="color:var(--mut);font-weight:400;
  font-size:12px">(cross-user median, shaded IQR; dotted: real holdout
  reference; dash-dot: surrogate floors — "binomial" = constant-rate,
  "clock" = hour-of-day rate; per-user lines via the toggle above)</span></h2>
<div class="panels" id="panels"></div>

<h2>Cohort summary — selected run <span style="color:var(--mut);
  font-weight:400;font-size:12px">(median and IQR across users; per-user
  numbers are in the drill-down below)</span></h2>
<div style="overflow-x:auto"><table id="runtable"></table></div>

<details>
  <summary>Per-user detail (metric × iteration, one user at a time)</summary>
  <div class="controls">
    <label for="usersel">User</label>
    <select id="usersel"></select>
    <a id="tracelink" href="#">trace-browser page for this user</a>
  </div>
  <div style="overflow-x:auto"><table id="usertable"></table></div>
</details>

<h2>Iteration log</h2>
<div style="overflow-x:auto"><table id="runlog"></table></div>
<div id="tooltip"></div>

<script>
const DATA = __DATA__;

const ORDER = DATA.runs.map(r => r.label);
const USERS = DATA.users;
// per-user hue identity caps at the validated palette (hues are never
// cycled); beyond it, panels switch to muted per-user lines + a median line,
// with identity available via hover and the run table
const SPAGHETTI = USERS.length > DATA.user_colors.length;
const GRAY = "#898781";
const COLOR = Object.fromEntries(USERS.map((u, i) =>
  [u, SPAGHETTI ? GRAY : DATA.user_colors[i]]));
const median = arr => {
  const v = arr.filter(x => x !== null && x !== undefined && !Number.isNaN(x))
    .sort((a, b) => a - b);
  if (!v.length) return null;
  const m = Math.floor(v.length / 2);
  return v.length % 2 ? v[m] : (v[m - 1] + v[m]) / 2;
};
const CELL = {};   // run -> user -> metric -> {value, sd}
for (const row of DATA.rows) {
  ((CELL[row.run_label] ??= {})[row.user] ??= {})[row.metric] = row;
}
const fmt = v => (v === null || v === undefined || Number.isNaN(v)) ? "–"
  : String(Number(Number(v).toPrecision(4)));
const cellText = c => !c || c.value === null ? "–"
  : fmt(c.value) + (c.sd !== null && c.sd !== undefined ? " ±" + Number(Number(c.sd).toPrecision(2)) : "");

const TIER_LABEL = {context: "Context", fit: "Holdout fit (one-step-ahead)",
                    simulation: "Simulation (free-running, mean ±sd)"};
function tier(metric) { return TIER_LABEL[DATA.tiers[metric]] || "Context"; }

function showUsersOn() {
  return document.getElementById("showusers").checked;
}

function renderLegend() {
  const leg = document.getElementById("legend");
  leg.innerHTML = SPAGHETTI
    ? `<span><span class="dot" style="background:${DATA.user_colors[0]}"></span>` +
      `median across users (shaded: IQR)</span>` +
      (showUsersOn()
        ? `<span><span class="dot" style="background:${GRAY};opacity:.5"></span>` +
          `individual users (n=${USERS.length}, hover for identity)</span>`
        : "")
    : USERS.map(u =>
      `<span><span class="dot" style="background:${COLOR[u]}"></span>${u}</span>`).join("");
}

function renderSub() {
  document.getElementById("sub").textContent =
    `generated ${DATA.generated} · ${DATA.runs.length} run(s) · ${USERS.length} user(s)`;
  const link = u => `<a href="../${u}/traces.html">${u}</a>`;
  const sets = DATA.user_sets || {};
  const train = sets.train || [], dev = sets.dev || [];
  let strip = `traces: <a href="../traces_index.html">cohort index</a>`;
  if (train.length || dev.length) {
    // train/dev columns in span-rank order (the user_sets parity rule);
    // history users missing from users.csv (stale export) keep their links
    const listed = new Set(train.concat(dev).map(p => p[1]));
    const other = USERS.filter(u => !listed.has(u));
    const col = (name, rows) => `<div><div class="setname">${name}</div>` +
      rows.map(p => `<div><span class="rk">${p[0]}</span> ${link(p[1])}</div>`)
        .join("") + `</div>`;
    strip += `<div class="usercols">` +
      col(`train users (n=${train.length}) — iterate here`, train) +
      col(`dev users (n=${dev.length}) — held out`, dev) + `</div>` +
      (other.length ? `<div>not in users.csv: ${other.map(link).join(" · ")}</div>` : "");
  } else {
    strip += ` · ` + USERS.map(link).join(" · ");
  }
  document.getElementById("tracestrip").innerHTML = strip;
  const sel = document.getElementById("runsel");
  sel.innerHTML = ORDER.map(l => `<option value="${l}">${l}</option>`).join("");
  sel.value = ORDER[ORDER.length - 1];
  sel.onchange = render;
  const usel = document.getElementById("usersel");
  usel.innerHTML = USERS.map(u => `<option value="${u}">${u}</option>`).join("");
  usel.value = USERS[0];
  usel.onchange = render;
  document.getElementById("showusers").onchange = render;
}

function renderConfig(run) {
  const r = DATA.runs.find(x => x.label === run);
  const s = r.config.split || {};
  document.getElementById("config").textContent =
    `recorded ${r.ts} · commit ${r.commit} · split ${s.type ?? "?"} ` +
    `(train_frac ${s.train_frac ?? "?"}) · n_sims ${r.config.n_sims ?? "?"}` +
    (r.config.user_set && r.config.user_set !== "all"
      ? ` · ${r.config.user_set} user set` : "") +
    ` · comparisons are like-for-like only within a split regime`;
  document.getElementById("runnote").textContent = r.note || "";
}

function renderRunLog(selectedRun) {
  const t = document.getElementById("runlog");
  t.innerHTML = `<tr><th>iteration</th><th>recorded</th><th>split</th>` +
    `<th style="text-align:left">note</th></tr>` +
    DATA.runs.map(r => {
      const s = r.config.split || {};
      const bold = r.label === selectedRun ? "font-weight:650" : "";
      return `<tr><td style="text-align:left;${bold}">${r.label}</td>` +
        `<td>${String(r.ts).slice(0, 10)}</td>` +
        `<td>${s.type ?? "?"}</td>` +
        `<td style="text-align:left;color:var(--sec)">${r.note || ""}</td></tr>`;
    }).join("");
}

function attachMetricTips(t) {
  for (const td of t.querySelectorAll("td.metric")) {
    const m = td.dataset.m;
    const desc = DATA.descriptions[m];
    if (!desc) continue;
    td.addEventListener("mousemove", evt => showTip(evt, [m, desc]));
    td.addEventListener("mouseleave", hideTip);
  }
}

const quantile = (arr, q) => {
  const v = arr.filter(x => x !== null && x !== undefined && !Number.isNaN(x))
    .sort((a, b) => a - b);
  if (!v.length) return null;
  const pos = (v.length - 1) * q, lo = Math.floor(pos);
  return lo === pos ? v[lo] : v[lo] + (v[lo + 1] - v[lo]) * (pos - lo);
};

function renderSummary(run) {
  const t = document.getElementById("runtable");
  let html = `<tr><th>metric</th><th>median</th><th>IQR</th><th>n users</th></tr>`;
  let lastTier = null;
  for (const m of DATA.metric_order) {
    const tr = tier(m);
    if (tr !== lastTier) {
      html += `<tr class="tier"><td colspan="4">${tr}</td></tr>`;
      lastTier = tr;
    }
    const vals = USERS.map(u => (CELL[run]?.[u]?.[m] ?? {}).value ?? null)
      .filter(v => v !== null && v !== undefined && !Number.isNaN(v));
    html += `<tr><td class="metric" data-m="${m}">${m}</td>` +
      `<td>${fmt(median(vals))}</td>` +
      `<td>${vals.length ? `${fmt(quantile(vals, 0.25))} … ${fmt(quantile(vals, 0.75))}` : "–"}</td>` +
      `<td>${vals.length}</td></tr>`;
  }
  t.innerHTML = html;
  attachMetricTips(t);
}

function renderUserDetail(selectedRun) {
  const u = document.getElementById("usersel").value;
  document.getElementById("tracelink").href = `../${u}/traces.html`;
  const runs = ORDER.filter(r => CELL[r]?.[u]);
  const t = document.getElementById("usertable");
  let html = `<tr><th>metric</th>` + runs.map(r =>
    `<th style="${r === selectedRun ? "color:var(--ink)" : ""}">${r}</th>`).join("") + `</tr>`;
  let lastTier = null;
  for (const m of DATA.metric_order) {
    const tr = tier(m);
    if (tr !== lastTier) {
      html += `<tr class="tier"><td colspan="${runs.length + 1}">${tr}</td></tr>`;
      lastTier = tr;
    }
    html += `<tr><td class="metric" data-m="${m}">${m}</td>` +
      runs.map(r => `<td>${cellText(CELL[r]?.[u]?.[m])}</td>`).join("") + `</tr>`;
  }
  t.innerHTML = html;
  attachMetricTips(t);
}

const TT = document.getElementById("tooltip");
function showTip(evt, lines) {
  TT.innerHTML = lines.map((l, i) => i ? `<div class="t2">${l}</div>` : `<div>${l}</div>`).join("");
  TT.style.display = "block";
  TT.style.left = Math.min(evt.clientX + 14, innerWidth - 340) + "px";
  TT.style.top = (evt.clientY + 14) + "px";
}
function hideTip() { TT.style.display = "none"; }

function svgEl(tag, attrs) {
  const el = document.createElementNS("http://www.w3.org/2000/svg", tag);
  for (const [k, v] of Object.entries(attrs)) el.setAttribute(k, v);
  return el;
}

function panel(metric, title, selectedRun) {
  const W = 540, H = 300, L = 52, R = 14, T = 12, B = 66;
  const ref = DATA.reference[metric] || {};
  const series = USERS.map(u => ({
    user: u,
    pts: ORDER.map(run => CELL[run]?.[u]?.[metric] ?? null),
    real: ref.real_ref ? ORDER.map(run => CELL[run]?.[u]?.[ref.real_ref] ?? null) : null,
  }));

  // surrogate floors: cross-user median per run, drawn as labeled dash-dot
  // references ("binomial" = constant-rate, "clock" = hour-of-day-rate)
  const surrFloors = (ref.surr_refs || []).map(([m, label]) => ({
    label,
    vals: ORDER.map(run =>
      median(USERS.map(u => (CELL[run]?.[u]?.[m] ?? {}).value ?? null))),
  })).filter(f => f.vals.some(v => v !== null));

  // with per-user lines hidden, the y-range fits the cohort view (median,
  // IQR, references) instead of stretching to every user's extremes
  const collapse = SPAGHETTI && !showUsersOn();
  const valsAt = i => series.map(s => s.pts[i] ? s.pts[i].value : null)
    .filter(v => v !== null && v !== undefined && !Number.isNaN(v));
  const rmed = i => median(series.map(s => s.real && s.real[i] ? s.real[i].value : null));
  const vals = [];
  if (collapse) {
    ORDER.forEach((_, i) => {
      const v = valsAt(i);
      if (v.length) vals.push(median(v), quantile(v, 0.25), quantile(v, 0.75));
      if (ref.real_ref && rmed(i) !== null) vals.push(rmed(i));
    });
  } else {
    for (const s of series) {
      for (const p of s.pts) if (p && p.value !== null) {
        vals.push(p.value); if (p.sd) { vals.push(p.value + p.sd, p.value - p.sd); }
      }
      if (s.real) for (const p of s.real) if (p && p.value !== null) vals.push(p.value);
    }
  }
  for (const f of surrFloors) for (const v of f.vals) if (v !== null) vals.push(v);
  if (ref.band) vals.push(ref.band[0], ref.band[1]);
  if (ref.line !== undefined) vals.push(ref.line);
  if (!vals.length) return null;
  let lo = Math.min(...vals), hi = Math.max(...vals);
  if (lo === hi) { lo -= 0.5; hi += 0.5; }
  const pad = (hi - lo) * 0.09; lo -= pad; hi += pad;

  const x = i => L + (ORDER.length === 1 ? (W - L - R) / 2
    : i * (W - L - R) / (ORDER.length - 1));
  const y = v => T + (H - T - B) * (1 - (v - lo) / (hi - lo));

  const div = document.createElement("div");
  div.className = "panel";
  div.innerHTML = `<div><span class="ptitle">${title}</span></div>`;
  attachTitleTip(div, metric);
  const svg = svgEl("svg", {width: W, height: H});
  div.appendChild(svg);

  if (ref.band) svg.appendChild(svgEl("rect", {
    x: L, y: y(ref.band[1]), width: W - L - R,
    height: Math.max(0, y(ref.band[0]) - y(ref.band[1])),
    fill: "var(--band)"}));
  for (let t = 0; t < 4; t++) {                       // y grid + labels
    const v = lo + (hi - lo) * t / 3;
    svg.appendChild(svgEl("line", {x1: L, x2: W - R, y1: y(v), y2: y(v),
      stroke: "var(--grid)", "stroke-width": 0.8}));
    const lab = svgEl("text", {x: L - 6, y: y(v) + 3.5, "text-anchor": "end",
      fill: "var(--mut)", "font-size": 10});
    lab.textContent = fmt(v);
    svg.appendChild(lab);
  }
  if (ref.line !== undefined) svg.appendChild(svgEl("line", {
    x1: L, x2: W - R, y1: y(ref.line), y2: y(ref.line),
    stroke: "var(--baseline)", "stroke-dasharray": "5 4"}));

  for (const f of surrFloors) {
    const seg = f.vals.map((v, i) => v !== null ? `${x(i)},${y(v)}` : null)
      .filter(Boolean);
    svg.appendChild(svgEl("polyline", {points: seg.join(" "), fill: "none",
      stroke: GRAY, "stroke-width": 1.1, "stroke-dasharray": "4 2 1 2"}));
    let last = null;
    f.vals.forEach((v, i) => { if (v !== null) {
      svg.appendChild(svgEl("rect", {x: x(i) - 2.5, y: y(v) - 2.5, width: 5,
        height: 5, fill: "none", stroke: GRAY}));
      last = [x(i), y(v)];
    }});
    if (last) {
      const lab = svgEl("text", {x: last[0] + 5, y: last[1] - 4,
        fill: "var(--mut)", "font-size": 9});
      lab.textContent = f.label;
      svg.appendChild(lab);
    }
  }

  ORDER.forEach((run, i) => {                         // x labels
    const lab = svgEl("text", {
      x: x(i), y: H - B + 16, fill: run === selectedRun ? "var(--ink)" : "var(--mut)",
      "font-size": 10, "font-weight": run === selectedRun ? 650 : 400,
      transform: `rotate(-28 ${x(i)} ${H - B + 16})`, "text-anchor": "end"});
    lab.textContent = run;
    svg.appendChild(lab);
  });

  if (SPAGHETTI) {
    const seg = pts => pts.filter(p => p !== null).join(" ");
    // IQR band across users, drawn under everything else in this layer
    const band_pts = ORDER.map((_, i) => {
      const v = valsAt(i);
      return v.length >= 3
        ? [x(i), y(quantile(v, 0.25)), y(quantile(v, 0.75))] : null;
    }).filter(Boolean);
    if (band_pts.length >= 2) {
      svg.appendChild(svgEl("polygon", {
        points: band_pts.map(([bx, , yhi]) => `${bx},${yhi}`)
          .concat(band_pts.map(([bx, ylo]) => `${bx},${ylo}`).reverse()).join(" "),
        fill: DATA.user_colors[0], opacity: 0.10}));
    }
    if (showUsersOn()) {
      for (const s of series) {
        svg.appendChild(svgEl("polyline", {
          points: seg(s.pts.map((p, i) => p && p.value !== null ? `${x(i)},${y(p.value)}` : null)),
          fill: "none", stroke: GRAY, "stroke-width": 0.9, opacity: 0.4}));
      }
    }
    const med = i => median(series.map(s => s.pts[i] ? s.pts[i].value : null));
    if (ref.real_ref) {
      svg.appendChild(svgEl("polyline", {
        points: seg(ORDER.map((_, i) => rmed(i) !== null ? `${x(i)},${y(rmed(i))}` : null)),
        fill: "none", stroke: DATA.user_colors[0], "stroke-width": 1.2,
        opacity: 0.7, "stroke-dasharray": "2 3"}));
      ORDER.forEach((_, i) => { const v = rmed(i); if (v !== null)
        svg.appendChild(svgEl("circle", {cx: x(i), cy: y(v), r: 3,
          fill: "none", stroke: DATA.user_colors[0], opacity: 0.7})); });
    }
    svg.appendChild(svgEl("polyline", {
      points: seg(ORDER.map((_, i) => med(i) !== null ? `${x(i)},${y(med(i))}` : null)),
      fill: "none", stroke: DATA.user_colors[0], "stroke-width": 2.2}));
    ORDER.forEach((run, i) => { const v = med(i); if (v !== null) {
      svg.appendChild(svgEl("circle", {cx: x(i), cy: y(v), r: 4,
        fill: DATA.user_colors[0], stroke: "var(--surface)", "stroke-width": 1.5}));
      const n = valsAt(i).length;
      const hit = svgEl("circle", {cx: x(i), cy: y(v), r: 9, fill: "transparent"});
      hit.addEventListener("mousemove", evt =>
        showTip(evt, [`median — ${ORDER[i]}`,
                      `${metric}: ${fmt(v)} (n=${n} users)`]));
      hit.addEventListener("mouseleave", hideTip);
      svg.appendChild(hit);
    }});
    if (showUsersOn()) {
      // identity via hover: a hit circle on every user point
      for (const s of series) s.pts.forEach((p, i) => {
        if (!p || p.value === null) return;
        const hit = svgEl("circle", {cx: x(i), cy: y(p.value), r: 7,
          fill: "transparent"});
        hit.addEventListener("mousemove", evt =>
          showTip(evt, [`${s.user} — ${ORDER[i]}`, `${metric}: ${cellText(p)}`]));
        hit.addEventListener("mouseleave", hideTip);
        svg.appendChild(hit);
      });
    }
    return div;
  }

  series.forEach((s, si) => {
    const off = (si - (USERS.length - 1) / 2) * 5;
    const col = COLOR[s.user];
    if (s.real) {
      const seg = s.real.map((p, i) => p && p.value !== null ? `${x(i) + off},${y(p.value)}` : null);
      svg.appendChild(svgEl("polyline", {points: seg.filter(Boolean).join(" "),
        fill: "none", stroke: col, "stroke-width": 1, opacity: 0.55,
        "stroke-dasharray": "2 3"}));
      s.real.forEach((p, i) => { if (p && p.value !== null) svg.appendChild(svgEl("circle",
        {cx: x(i) + off, cy: y(p.value), r: 3, fill: "none", stroke: col,
         opacity: 0.55})); });
    }
    const seg = s.pts.map((p, i) => p && p.value !== null ? `${x(i) + off},${y(p.value)}` : null);
    svg.appendChild(svgEl("polyline", {points: seg.filter(Boolean).join(" "),
      fill: "none", stroke: col, "stroke-width": 1.8}));
    s.pts.forEach((p, i) => {
      if (!p || p.value === null) return;
      const cx = x(i) + off;
      if (p.sd) {
        svg.appendChild(svgEl("line", {x1: cx, x2: cx, y1: y(p.value - p.sd),
          y2: y(p.value + p.sd), stroke: col, "stroke-width": 1}));
        for (const e of [p.value - p.sd, p.value + p.sd])
          svg.appendChild(svgEl("line", {x1: cx - 3, x2: cx + 3, y1: y(e), y2: y(e),
            stroke: col, "stroke-width": 1}));
      }
      svg.appendChild(svgEl("circle", {cx, cy: y(p.value), r: 3.5, fill: col,
        stroke: "var(--surface)", "stroke-width": 1.5}));
      const hit = svgEl("circle", {cx, cy: y(p.value), r: 11, fill: "transparent"});
      hit.addEventListener("mousemove", evt => {
        const lines = [`${s.user} — ${ORDER[i]}`, `${metric}: ${cellText(p)}`];
        if (s.real && s.real[i] && s.real[i].value !== null)
          lines.push(`real holdout: ${fmt(s.real[i].value)}`);
        showTip(evt, lines);
      });
      hit.addEventListener("mouseleave", hideTip);
      svg.appendChild(hit);
    });
  });
  return div;
}

// ---- selected-run ROC section --------------------------------------------
// median/IQR across users are taken vertically at a fixed FPR grid; vertical
// jumps in a step curve resolve to their upper TPR
const ROC_GRID = Array.from({length: 51}, (_, i) => i / 50);

function interpTpr(curve, f) {
  for (let i = 1; i < curve.length; i++) {
    const f0 = curve[i - 1][0], t0 = curve[i - 1][1];
    const f1 = curve[i][0], t1 = curve[i][1];
    if (f <= f1) return f1 === f0 ? Math.max(t0, t1)
      : t0 + (t1 - t0) * (f - f0) / (f1 - f0);
  }
  return curve[curve.length - 1][1];
}

function rocGridStats(curves) {
  return ROC_GRID.map(f => {
    const ts = curves.map(c => interpTpr(c, f));
    return {f, med: median(ts), q1: quantile(ts, 0.25),
            q3: quantile(ts, 0.75), n: ts.length};
  });
}

function attachTitleTip(div, metric) {
  const desc = DATA.descriptions[metric];
  if (!desc) return;
  const pt = div.querySelector(".ptitle");
  pt.addEventListener("mousemove", evt => showTip(evt, [metric, desc]));
  pt.addEventListener("mouseleave", hideTip);
}

function rocPanel(prefix, run) {
  const W = 360, H = 336, L = 46, R = 14, T = 14, B = 44;
  const x = f => L + f * (W - L - R);
  const y = t => T + (H - T - B) * (1 - t);
  const div = document.createElement("div");
  div.className = "panel";
  div.innerHTML = `<div><span class="ptitle">ROC (holdout, one-step-ahead)</span></div>`;
  attachTitleTip(div, prefix + "_auc");
  const svg = svgEl("svg", {width: W, height: H});
  div.appendChild(svg);

  for (const v of [0, 0.25, 0.5, 0.75, 1]) {          // grid + tick labels
    svg.appendChild(svgEl("line", {x1: x(v), x2: x(v), y1: y(0), y2: y(1),
      stroke: "var(--grid)", "stroke-width": 0.8}));
    svg.appendChild(svgEl("line", {x1: x(0), x2: x(1), y1: y(v), y2: y(v),
      stroke: "var(--grid)", "stroke-width": 0.8}));
    const xl = svgEl("text", {x: x(v), y: y(0) + 13, "text-anchor": "middle",
      fill: "var(--mut)", "font-size": 10});
    xl.textContent = v;
    svg.appendChild(xl);
    const yl = svgEl("text", {x: x(0) - 6, y: y(v) + 3.5, "text-anchor": "end",
      fill: "var(--mut)", "font-size": 10});
    yl.textContent = v;
    svg.appendChild(yl);
  }
  const xt = svgEl("text", {x: (x(0) + x(1)) / 2, y: H - 4,
    "text-anchor": "middle", fill: "var(--sec)", "font-size": 10.5});
  xt.textContent = "false positive rate";
  svg.appendChild(xt);
  const ymid = (y(0) + y(1)) / 2;
  const yt = svgEl("text", {x: 11, y: ymid, "text-anchor": "middle",
    fill: "var(--sec)", "font-size": 10.5, transform: `rotate(-90 11 ${ymid})`});
  yt.textContent = "true positive rate";
  svg.appendChild(yt);

  svg.appendChild(svgEl("line", {x1: x(0), y1: y(0), x2: x(1), y2: y(1),
    stroke: "var(--baseline)", "stroke-dasharray": "5 4"}));
  const ang = Math.atan2(y(1) - y(0), x(1) - x(0)) * 180 / Math.PI;
  const ch = svgEl("text", {x: x(0.62), y: y(0.56), "text-anchor": "middle",
    fill: "var(--mut)", "font-size": 9,
    transform: `rotate(${ang} ${x(0.62)} ${y(0.56)})`});
  ch.textContent = "chance (binomial)";
  svg.appendChild(ch);

  const byUser = DATA.roc[run] || {};
  const rocUsers = USERS.filter(u =>
    byUser[u] && byUser[u][prefix] && byUser[u][prefix].model);
  const clockCurves = rocUsers.map(u => byUser[u][prefix].clock).filter(Boolean);
  const binomCurves = rocUsers.map(u => byUser[u][prefix].binomial).filter(Boolean);
  const toPts = stats => stats.map(g => `${x(g.f)},${y(g.med)}`).join(" ");

  if (binomCurves.length) {
    // recorded binomial ROC -- computed from the constant-rate predictor,
    // which ties every tick, so it lies exactly on the chance diagonal;
    // drawing it over the dashed line marks the floor as recorded data
    svg.appendChild(svgEl("polyline", {
      points: toPts(rocGridStats(binomCurves)), fill: "none", stroke: GRAY,
      "stroke-width": 1.3, "stroke-dasharray": "4 2 1 2"}));
  }
  if (clockCurves.length) {                            // clock surrogate floor
    const cs = rocGridStats(clockCurves);
    svg.appendChild(svgEl("polyline", {points: toPts(cs), fill: "none",
      stroke: GRAY, "stroke-width": 1.3, "stroke-dasharray": "4 2 1 2"}));
    const at = cs[Math.round(0.22 * (cs.length - 1))];
    const lab = svgEl("text", {x: x(at.f) + 6, y: y(at.med) + 11,
      fill: "var(--mut)", "font-size": 9});
    lab.textContent = "clock";
    svg.appendChild(lab);
  }

  if (rocUsers.length) {
    if (!SPAGHETTI || showUsersOn()) {                 // per-user model curves
      for (const u of rocUsers) {
        const pts = byUser[u][prefix].model
          .map(p => `${x(p[0])},${y(p[1])}`).join(" ");
        svg.appendChild(svgEl("polyline", {points: pts, fill: "none",
          stroke: SPAGHETTI ? GRAY : COLOR[u],
          "stroke-width": SPAGHETTI ? 0.9 : 1.8,
          opacity: SPAGHETTI ? 0.4 : 1}));
        const hit = svgEl("polyline", {points: pts, fill: "none",
          stroke: "transparent", "stroke-width": 9});
        hit.addEventListener("mousemove", evt => showTip(evt,
          [`${u} — model ROC`,
           `AUC: ${fmt((CELL[run]?.[u]?.[prefix + "_auc"] ?? {}).value)}`]));
        hit.addEventListener("mouseleave", hideTip);
        svg.appendChild(hit);
      }
    }
    if (SPAGHETTI) {                                   // median + IQR band
      const ms = rocGridStats(rocUsers.map(u => byUser[u][prefix].model));
      if (rocUsers.length >= 3) {
        svg.appendChild(svgEl("polygon", {points:
          ms.map(g => `${x(g.f)},${y(g.q3)}`).concat(
            ms.slice().reverse().map(g => `${x(g.f)},${y(g.q1)}`)).join(" "),
          fill: DATA.user_colors[0], opacity: 0.10}));
      }
      svg.appendChild(svgEl("polyline", {points: toPts(ms), fill: "none",
        stroke: DATA.user_colors[0], "stroke-width": 2.2}));
      const hit = svgEl("polyline", {points: toPts(ms), fill: "none",
        stroke: "transparent", "stroke-width": 10});
      hit.addEventListener("mousemove", evt => {
        const rect = svg.getBoundingClientRect();
        const f = Math.min(1, Math.max(0,
          (evt.clientX - rect.left - L) / (W - L - R)));
        const g = ms.reduce((a, b) =>
          Math.abs(b.f - f) < Math.abs(a.f - f) ? b : a);
        showTip(evt, [`model — median of ${g.n} users`,
          `FPR ${(g.f * 100).toFixed(0)}% → TPR ${(g.med * 100).toFixed(0)}%`]);
      });
      hit.addEventListener("mouseleave", hideTip);
      svg.appendChild(hit);
    }
  } else {                                             // pre-ROC-era run
    const lines = ["ROC not recorded for this run",
                   "re-run this label to record curves"];
    lines.forEach((s, i) => {
      const n = svgEl("text", {x: x(0.35), y: y(0.78) + i * 15,
        "text-anchor": "middle", fill: "var(--mut)", "font-size": i ? 10 : 11});
      n.textContent = s;
      svg.appendChild(n);
    });
  }

  // the recorded AUCs behind the curves (median [IQR] across users)
  const vals = met => USERS.map(u => (CELL[run]?.[u]?.[met] ?? {}).value)
    .filter(v => v !== null && v !== undefined && !Number.isNaN(v));
  const mv = vals(prefix + "_auc");
  const cv = vals("surr_diurnal_" + prefix + "_auc");
  const bv = vals("surr_const_" + prefix + "_auc");
  if (mv.length) {
    const a1 = svgEl("text", {x: x(0.97), y: y(0.135), "text-anchor": "end",
      fill: "var(--ink)", "font-size": 10.5, "font-weight": 600});
    a1.textContent = `AUC model ${fmt(median(mv))}` + (mv.length > 1
      ? ` [${fmt(quantile(mv, 0.25))} … ${fmt(quantile(mv, 0.75))}]` : "");
    svg.appendChild(a1);
    const a2 = svgEl("text", {x: x(0.97), y: y(0.06), "text-anchor": "end",
      fill: "var(--mut)", "font-size": 10.5});
    a2.textContent = (cv.length ? `AUC clock ${fmt(median(cv))}`
                                : "AUC clock: not recorded") +
      (bv.length ? ` · binomial ${fmt(median(bv))}` : " · chance 0.5");
    svg.appendChild(a2);
  }
  return div;
}

function aucStrip(prefix, run) {
  const rows = USERS.map(u => ({
    user: u,
    model: (CELL[run]?.[u]?.[prefix + "_auc"] ?? {}).value ?? null,
    clock: (CELL[run]?.[u]?.["surr_diurnal_" + prefix + "_auc"] ?? {}).value ?? null,
  })).filter(r => r.model !== null && !Number.isNaN(r.model));
  if (!rows.length) return null;
  rows.sort((a, b) => b.model - a.model);
  const hasClock = r => r.clock !== null && !Number.isNaN(r.clock);
  const anyClock = rows.some(hasClock);

  const W = 360, L = 16, R = 16, T = 10, rowH = 15, B = anyClock ? 40 : 52;
  const H = T + rows.length * rowH + B;
  const all = rows.flatMap(r => [r.model, r.clock])
    .filter(v => v !== null && !Number.isNaN(v)).concat([0.5]);
  let lo = Math.min(...all), hi = Math.max(...all);
  const pad = (hi - lo) * 0.07 + 0.01;
  lo -= pad; hi += pad;
  const x = v => L + (v - lo) / (hi - lo) * (W - L - R);
  const yBot = T + rows.length * rowH;

  const div = document.createElement("div");
  div.className = "panel";
  div.innerHTML = `<div><span class="ptitle">rank AUC per user — ` +
    `model dot vs clock-floor square (sorted by model)</span></div>`;
  attachTitleTip(div, prefix + "_auc");
  const svg = svgEl("svg", {width: W, height: H});
  div.appendChild(svg);

  const ticks = [];
  for (let t = Math.ceil(lo * 10) / 10; t <= hi + 1e-9;
       t = Math.round((t + 0.1) * 10) / 10)
    ticks.push(Math.round(t * 10) / 10);
  for (const v of ticks) {
    svg.appendChild(svgEl("line", {x1: x(v), x2: x(v), y1: T, y2: yBot,
      stroke: "var(--grid)", "stroke-width": 0.8}));
    const lab = svgEl("text", {x: x(v), y: yBot + 13, "text-anchor": "middle",
      fill: "var(--mut)", "font-size": 10});
    lab.textContent = v;
    svg.appendChild(lab);
  }
  if (lo < 0.5 && hi > 0.5) {
    svg.appendChild(svgEl("line", {x1: x(0.5), x2: x(0.5), y1: T, y2: yBot,
      stroke: "var(--baseline)", "stroke-dasharray": "5 4"}));
    const lab = svgEl("text", {x: x(0.5), y: yBot + 25,
      "text-anchor": "middle", fill: "var(--mut)", "font-size": 9});
    lab.textContent = "chance (binomial)";
    svg.appendChild(lab);
  }
  if (!anyClock) {
    const note = svgEl("text", {x: L, y: yBot + (ticks.length ? 39 : 25),
      fill: "var(--mut)", "font-size": 10});
    note.textContent = "clock floor not recorded for this run — re-run this label";
    svg.appendChild(note);
  }

  rows.forEach((r, i) => {
    const cy = T + (i + 0.5) * rowH;
    if (hasClock(r)) {
      svg.appendChild(svgEl("line", {x1: x(r.clock), x2: x(r.model),
        y1: cy, y2: cy, stroke: "var(--grid)", "stroke-width": 1.4}));
      svg.appendChild(svgEl("rect", {x: x(r.clock) - 3, y: cy - 3, width: 6,
        height: 6, fill: "var(--surface)", stroke: GRAY, "stroke-width": 1.2}));
    }
    svg.appendChild(svgEl("circle", {cx: x(r.model), cy, r: 4,
      fill: SPAGHETTI ? DATA.user_colors[0] : COLOR[r.user],
      stroke: "var(--surface)", "stroke-width": 1.2}));
    const hit = svgEl("rect", {x: L, y: cy - rowH / 2, width: W - L - R,
      height: rowH, fill: "transparent"});
    hit.addEventListener("mousemove", evt => showTip(evt,
      [r.user, `model AUC ${fmt(r.model)}` +
       (hasClock(r) ? ` · clock ${fmt(r.clock)}` : "")]));
    hit.addEventListener("mouseleave", hideTip);
    svg.appendChild(hit);
  });
  return div;
}

function renderRoc(run) {
  const host = document.getElementById("rocpanels");
  host.innerHTML = "";
  for (const head of DATA.pair_column_heads) {
    const d = document.createElement("div");
    d.className = "colhead";
    d.textContent = head;
    host.appendChild(d);
  }
  for (const prefix of ["corr", "carb"]) host.appendChild(rocPanel(prefix, run));
  for (const prefix of ["corr", "carb"])
    host.appendChild(aucStrip(prefix, run) ?? document.createElement("div"));
}

function renderPanels(selectedRun) {
  const host = document.getElementById("panels");
  host.innerHTML = "";
  for (const head of DATA.pair_column_heads) {
    const d = document.createElement("div");
    d.className = "colhead";
    d.textContent = head;
    host.appendChild(d);
  }
  for (const pair of DATA.key_metric_pairs)
    for (const [metric, title] of pair)
      // empty placeholder keeps the two-column pairing aligned when one
      // side has no data yet
      host.appendChild(panel(metric, title, selectedRun) ??
                       document.createElement("div"));
}

function render() {
  const run = document.getElementById("runsel").value;
  renderLegend();
  renderConfig(run);
  renderRoc(run);
  renderSummary(run);
  renderUserDetail(run);
  renderPanels(run);
  renderRunLog(run);
}

renderSub();
render();
</script>
</body>
</html>
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--history", default=DEFAULT_HISTORY)
    parser.add_argument("--out", default=None,
                        help=f"output path (default meta/{DASHBOARD_FILENAME})")
    args = parser.parse_args()
    build_dashboard(args.history, args.out)
